# numpy

NumPy is a powerful Python library for numerical computing, providing support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on them. It is fundamental for scientific computing and serves as the core building block for many other libraries in the Python ecosystem.

### np.array()

Creates an n-dimensional array whose data type you can specify.

In [3]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]

In [ ]:
type(mylist)

list

In [ ]:
arr_1d = np.array(mylist)

'''
We're calling the array function present in the np library. To this function, 'mylist' is passed as an argument
and the function returns an object of the ndarray class. We've named this object myarr.
(similar to naming int objects from the int class, so basically ndarray is like the fundamental dtype of np)
'''

arr_1d

array([1, 2, 3])

In [ ]:
list_2d = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]
list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr_2d = np.array(list_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Important attributes
`ndim`: number of dimensions (integer value)

`shape`: tuple containing dimensions of array

`size`: total number of elements in array

`dtype`: data type of the array

`T`: transpose of 2d array (matrix)

For a 1D array

In [ ]:
arr_1d

array([1, 2, 3])

In [ ]:
arr_1d.ndim

1

In [ ]:
arr_1d.shape

(3,)

In [ ]:
arr_1d.size

3

In [ ]:
arr_1d.dtype

dtype('int64')

In [ ]:
arr_1d.T # no change

array([1, 2, 3])

For a 2D array

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d.ndim

2

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d.size

9

In [ ]:
arr_2d.dtype

dtype('int64')

In [ ]:
print(f"Original: \n{arr_2d}")
print(f"Transpose: \n{arr_2d.T}")

Original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Array creation methods
`arange(start, stop, step)`: creates array with range of values (similar to `range()`)

`linspace(start, stop, qty)`: creates array of evenly spaced values over the closed interval [start, stop]

`zeros(tup)`: creates zero matrix

`ones(tup)`: creates matrix full of ones

`eye(side)`: creates identity matrix

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [ ]:
np.linspace(0, 10, 3, dtype=int)

array([ 0,  5, 10])

In [ ]:
np.zeros((3))

array([0., 0., 0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Important methods applied to arrays
`reshape(x, y)`: changes dimension of array to `(x, y)`

`flatten()`: flattens multi-dimensional array to 1-D array

`sum()`: sum of all elements of array

`sum(axis = 0)`: sum of columns of 2D array

`mean(), var(), std()`: mean, variance and standard deviation of array

`max(), min()`: max/min value in the array

`argmax(), argmin()`: index of max/min value in the array

`copy()`: copies array

`astype(dtype)`: casts the array to a specific type

In [ ]:
arr_2d = np.arange(0, 12).reshape(3, 4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr_2d.sum()

np.int64(66)

In [ ]:
arr_2d.sum(axis = 0) # sum of elements in columns 

array([12, 15, 18, 21])

In [ ]:
arr_2d.sum(axis = 1) # sum of elements in rows

array([ 6, 22, 38])

In [ ]:
arr_2d.mean()

np.float64(5.5)

In [ ]:
arr_2d.max()

np.int64(11)

In [ ]:
arr_2d.argmax() 

np.int64(11)

By default, argmax() flattens any n-dimensional array into a 1D array and then returns index in that flattened array.

In [ ]:
copy_2d = arr_2d.copy()
copy_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
copy_2d = copy_2d.astype(float)
copy_2d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### Array slicing

For a 1D array

In [ ]:
arr_1d = np.arange(0, 9)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr_1d[8]

np.int64(8)

In [ ]:
arr_1d[1: 3]

array([1, 2])

In [ ]:
arr_1d[3:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr_1d[-4: -1]

array([5, 6, 7])

In [ ]:
arr_1d[-4:]

array([5, 6, 7, 8])

In [ ]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
slice_of_arr_1d = arr_1d[0: 3]
slice_of_arr_1d

array([0, 1, 2])

In [ ]:
slice_of_arr_1d[:] = 10 
slice_of_arr_1d

array([10, 10, 10])

In [ ]:
arr_1d 

array([10, 10, 10,  3,  4,  5,  6,  7,  8])

Our original `arr_1d` also got changed. To make a change to the sliced array such that the original
one doesn't get changed, use a copy of `arr_1d`

In [ ]:
arr_1d = np.arange(0, 9)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
copy_arr_1d = np.copy(arr_1d)
slice_of_arr_1d = copy_arr_1d[0: 3]
slice_of_arr_1d

array([0, 1, 2])

In [ ]:
slice_of_arr_1d[:] = 10
slice_of_arr_1d

array([10, 10, 10])

In [ ]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

For a 2D array

In [ ]:
arr_2d = np.arange(0, 16).reshape(4, 4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr_2d[0:2, 1:3] # first two rows, second and third column

array([[1, 2],
       [5, 6]])

In [ ]:
arr_2d[2:4, :]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Conditional filtering

```python
filtered_array = original_array[condition]
```

`where(condition)` returns the indices where the condition is satisfied

`select(conditions, choices)` allows you to apply multiple conditions and choose between different values for each condition.

In [ ]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [ ]:
arr[(arr > 2) & (arr < 5)]

array([3, 4])

In [ ]:
indices = np.where(arr < 5)
indices

(array([0, 1, 2, 3, 4]),)

In [ ]:
conditions = [arr < 5, arr >= 5]
choices = [0, 1] # the data type of choices and original array should be same (in this case, int)

In [ ]:
np.select(conditions, choices)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Random submodule

`np.random` is a submodule in NumPy that provides a variety of random number generation capabilities.

Note: shapes aren't passed as tuples, normal commas.
E.g., np.random.rand(2, 3) -> 2x3 array

### Important methods
`rand(shape)`: array of random numbers

`random(shape - as tuple)`: random floats in interval `[0, 1)`

Note: both `rand` and `random` give same output, only difference is how you pass shape (rand is better)

`randn(shape)`: random numbers from a standard normal distrbution (mean = 0, std = 1)

`randint(start, stop, shape)`: random integers in closed interval [start, stop)

`uniform(lower, upper, shape)`: random numbers from uniform distribution over the interval `(lower, upper)`

`normal(mean, std, qty)`: `qty` random numbers from a normal (Gaussian) distribution with mean = `mean` and standard deviation = `std`

`shuffle()`: shuffles an array in place

`seed(n)`: to get same set of random stuff

In [ ]:
np.random.rand(3, 4)

array([[0.2839823 , 0.45948074, 0.33312392, 0.56753454],
       [0.41910548, 0.73457595, 0.54765541, 0.56602121],
       [0.7661969 , 0.36267619, 0.29861332, 0.30478271]])

In [ ]:
np.random.random((3, 4))

array([[0.17120409, 0.76697676, 0.82091115, 0.95905307],
       [0.50616383, 0.4138344 , 0.02314195, 0.07020649],
       [0.49254849, 0.97071718, 0.27911664, 0.67246706]])

In [ ]:
np.random.randn(3, 4)

array([[-0.78598755,  1.41312299,  0.51678352, -0.6634923 ],
       [-1.19492097,  2.27993992,  2.094096  , -0.81401746],
       [ 0.5067189 , -0.66816926,  0.71655056, -2.48157143]])

In [ ]:
np.random.randint(0, 10, (3,2))

array([[1, 6],
       [6, 8],
       [5, 5]])

In [ ]:
np.random.uniform(0, 10, (2,2))

array([[9.86446813, 6.48490714],
       [9.76423966, 9.7963251 ]])

In [ ]:
np.random.normal(0, 10, (3, 3))

array([[ -0.7084813 ,  -9.86485523,  13.06747394],
       [  3.39921206,  -1.74574766,   8.07111364],
       [-12.65458533, -12.63481206,  -2.65432363]])

In [ ]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(arr)
arr

array([5, 0, 9, 2, 6, 3, 7, 8, 4, 1])